VHDLSCOPE_APP_VERSION = 1.0
VHDLSCOPE_APP_SITE = $(BR2_EXTERNAL_VHDLSCOPE_PATH)/app_src
VHDLSCOPE_APP_SITE_METHOD = local
VHDLSCOPE_APP_LICENSE = GPL-2.0
VHDLSCOPE_APP_INSTALL_STAGING = NO
VHDLSCOPE_APP_INSTALL_TARGET = YES
#VHDL_SCOPE_MODULE_KCONFIG_FILE = $(BR2_EXTERNAL_VHDLSCOPE_PATH)/module_src/Kconfig


define VHDLSCOPE_APP_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/vhdlscope_app $(TARGET_DIR)/usr/bin
endef

$(eval $(cmake-package))