--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : CLK.vhd
-- /___/   /\     Timestamp : 12/29/2024 22:39:17
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st /home/pzdr/Projects/VHDL/VHDLscope/VHDLscope/ipcore_dir/./CLK.xaw /home/pzdr/Projects/VHDL/VHDLscope/VHDLscope/ipcore_dir/./CLK
--Design Name: CLK
--Device: xc3s50a-5tq144
--
-- Module CLK
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- Period Jitter (unit interval) for block DCM_SP_INST = 0.05 UI
-- Period Jitter (Peak-to-Peak) for block DCM_SP_INST = 0.83 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity CLK is
   port ( CE_IN           : in    std_logic; 
          CLKIN_IN        : in    std_logic; 
          RST_IN          : in    std_logic; 
          R_IN            : in    std_logic; 
          S_IN            : in    std_logic; 
          T_IN            : in    std_logic; 
          CLKFX_OUT       : out   std_logic; 
          CLKFX180_OUT    : out   std_logic; 
          CLKIN_IBUFG_OUT : out   std_logic; 
          CLK0_OUT        : out   std_logic; 
          CLK2X_OUT       : out   std_logic; 
          DDR_CLKFX_OUT   : out   std_logic; 
          LOCKED_OUT      : out   std_logic);
end CLK;

architecture BEHAVIORAL of CLK is
   signal CLKFB_IN        : std_logic;
   signal CLKFX_BUF       : std_logic;
   signal CLKFX180_BUF    : std_logic;
   signal CLKIN_IBUFG     : std_logic;
   signal CLK0_BUF        : std_logic;
   signal CLK2X_BUF       : std_logic;
   signal C0_IN           : std_logic;
   signal C1_IN           : std_logic;
   signal GND_BIT         : std_logic;
   signal VCC_BIT         : std_logic;
begin
   GND_BIT <= '0';
   VCC_BIT <= '1';
   CLKFX_OUT <= C0_IN;
   CLKFX180_OUT <= C1_IN;
   CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
   CLK2X_OUT <= CLKFB_IN;
   CLKFX_BUFG_INST : BUFG
      port map (I=>CLKFX_BUF,
                O=>C0_IN);
   
   CLKFX180_BUFG_INST : BUFG
      port map (I=>CLKFX180_BUF,
                O=>C1_IN);
   
   CLKIN_IBUFG_INST : IBUFG
      port map (I=>CLKIN_IN,
                O=>CLKIN_IBUFG);
   
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLK0_OUT);
   
   CLK2X_BUFG_INST : BUFG
      port map (I=>CLK2X_BUF,
                O=>CLKFB_IN);
   
   DCM_SP_INST : DCM_SP
   generic map( CLK_FEEDBACK => "2X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 5,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 83.333,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>open,
                CLKFX=>CLKFX_BUF,
                CLKFX180=>CLKFX180_BUF,
                CLK0=>CLK0_BUF,
                CLK2X=>CLK2X_BUF,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   OFDDRTRSE_INST : OFDDRTRSE
      port map (CE=>CE_IN,
                C0=>C0_IN,
                C1=>C1_IN,
                D0=>VCC_BIT,
                D1=>GND_BIT,
                R=>R_IN,
                S=>S_IN,
                T=>T_IN,
                O=>DDR_CLKFX_OUT);
   
end BEHAVIORAL;


